In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
path = '/content/drive/MyDrive/Final_project_2조/02_2. 전처리 및 EDA_이미지/data/annotation_data.csv'
path1 = '/content/drive/MyDrive/Final_project_2조/02_2. 전처리 및 EDA_이미지/data/measurement_data.csv'

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(path1, index_col = 0)

In [5]:
df.columns

Index(['ID', '수분_이마', '수분_오른쪽볼', '수분_왼쪽볼', '수분_턱', '탄력_턱_R0', '탄력_턱_R1',
       '탄력_턱_R2', '탄력_턱_R3', '탄력_턱_R4', '탄력_턱_R5', '탄력_턱_R6', '탄력_턱_R7',
       '탄력_턱_R8', '탄력_턱_R9', '탄력_턱_Q0', '탄력_턱_Q1', '탄력_턱_Q2', '탄력_턱_Q3',
       '탄력_왼쪽볼_R0', '탄력_왼쪽볼_R1', '탄력_왼쪽볼_R2', '탄력_왼쪽볼_R3', '탄력_왼쪽볼_R4',
       '탄력_왼쪽볼_R5', '탄력_왼쪽볼_R6', '탄력_왼쪽볼_R7', '탄력_왼쪽볼_R8', '탄력_왼쪽볼_R9',
       '탄력_왼쪽볼_Q0', '탄력_왼쪽볼_Q1', '탄력_왼쪽볼_Q2', '탄력_왼쪽볼_Q3', '탄력_오른쪽볼_R0',
       '탄력_오른쪽볼_R1', '탄력_오른쪽볼_R2', '탄력_오른쪽볼_R3', '탄력_오른쪽볼_R4', '탄력_오른쪽볼_R5',
       '탄력_오른쪽볼_R6', '탄력_오른쪽볼_R7', '탄력_오른쪽볼_R8', '탄력_오른쪽볼_R9', '탄력_오른쪽볼_Q0',
       '탄력_오른쪽볼_Q1', '탄력_오른쪽볼_Q2', '탄력_오른쪽볼_Q3', '탄력_이마_R0', '탄력_이마_R1',
       '탄력_이마_R2', '탄력_이마_R3', '탄력_이마_R4', '탄력_이마_R5', '탄력_이마_R6', '탄력_이마_R7',
       '탄력_이마_R8', '탄력_이마_R9', '탄력_이마_Q0', '탄력_이마_Q1', '탄력_이마_Q2', '탄력_이마_Q3',
       '주름_왼쪽눈가_Ra', '주름_왼쪽눈가_Rq', '주름_왼쪽눈가_Rmax', '주름_왼쪽눈가_R3z', '주름_왼쪽눈가_Rt',
       '주름_왼쪽눈가_Rz=Rtm', '주름_왼쪽눈가_Rp', '주름_왼쪽눈가_Rv', '주름_오른쪽눈가_Ra',
       '주름_오른쪽눈가_Rq', '주름_오른쪽눈가_Rmax', '주름_오른쪽눈가_R3z', '주름_오른쪽눈가_Rt',
       '주름_오른쪽눈가_Rz=Rtm', '주름_오른쪽눈가_Rp', '주름_오른쪽눈가_Rv', '스팟개수_정면', '모공개수_오른쪽볼',
       '모공개수_왼쪽볼'],
      dtype='object')

In [6]:
elasticity_l = df.filter(regex='탄력_왼쪽볼')
elasticity_l

elasticity_r = df.filter(regex='탄력_오른쪽볼')
elasticity_r

elasticity_f = df.filter(regex='탄력_이마')
elasticity_f

elasticity_chin = df.filter(regex='탄력_턱')
elasticity_chin

scaled_data = elasticity_r.탄력_오른쪽볼_R6 / 2
elasticity_r['탄력_오른쪽볼_R6'] = scaled_data

scaled_data = elasticity_l.탄력_왼쪽볼_R6 / 2
elasticity_l['탄력_왼쪽볼_R6'] = scaled_data

scaled_data = elasticity_f.탄력_이마_R6 / 2
elasticity_f['탄력_이마_R6'] = scaled_data

scaled_data = elasticity_chin.탄력_턱_R6 / 2
elasticity_chin['탄력_턱_R6'] = scaled_data

<ipython-input-6-a9cb1e941e8c>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elasticity_r['탄력_오른쪽볼_R6'] = scaled_data
<ipython-input-6-a9cb1e941e8c>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elasticity_l['탄력_왼쪽볼_R6'] = scaled_data
<ipython-input-6-a9cb1e941e8c>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elasticity_f['탄력_이마_R6'] = scaled_data
<ipython-input-6-a9cb1e941e8c>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elasticity_chin['탄력_턱_R6'] = scaled_data

In [7]:
feature1 = ['탄력_턱_R2', '탄력_턱_R5', '탄력_턱_R7', '탄력_턱_Q1', '탄력_턱_Q2', '탄력_턱_Q3']
feature2 = ['탄력_오른쪽볼_R2', '탄력_오른쪽볼_R5', '탄력_오른쪽볼_R7', '탄력_오른쪽볼_Q1', '탄력_오른쪽볼_Q2', '탄력_오른쪽볼_Q3']
pd.concat([elasticity_chin[feature1], elasticity_r[feature2]], axis=1)

,탄력_턱_R2,탄력_턱_R5,탄력_턱_R7,탄력_턱_Q1,탄력_턱_Q2,탄력_턱_Q3,탄력_오른쪽볼_R2,탄력_오른쪽볼_R5,탄력_오른쪽볼_R7,탄력_오른쪽볼_Q1,탄력_오른쪽볼_Q2,탄력_오른쪽볼_Q3
0,0.5931,0.6306,0.3431,0.5294,0.4281,0.1013,0.6522,0.6457,0.3565,0.5758,0.4465,0.1293
1,0.6846,0.5657,0.3548,0.6059,0.4571,0.1488,0.6331,0.6335,0.3669,0.5627,0.4490,0.1136
2,0.6187,0.5095,0.3573,0.5519,0.4449,0.1070,0.7129,0.7318,0.4323,0.6400,0.5259,0.1141
3,0.6265,0.6291,0.3815,0.5693,0.4632,0.1061,0.5429,0.4354,0.2791,0.4803,0.3533,0.1270
4,0.5126,0.6373,0.3266,0.4688,0.3963,0.0725,0.6274,0.7168,0.3821,0.5605,0.4624,0.0981
...,...,...,...,...,...,...,...,...,...,...,...,...
1067,0.6500,0.6400,0.4000,0.5800,0.4700,0.1100,0.6100,0.6000,0.3800,0.5500,0.4500,0.1000
1068,0.6900,0.5900,0.4300,0.6400,0.5200,0.1200,0.6100,0.5200,0.3600,0.5500,0.4400,0.1100
1069,0.6100,0.6200,0.3600,0.5400,0.4400,0.1100,0.6600,0.5400,0.3500,0.5900,0.4400,0.1400
1070,0.6700,0.6800,0.4200,0.6100,0.5000,0.1100,0.6300,0.5900,0.3700,0.5700,0.4600,0.1100
1071,0.7200,0.6900,0.4900,0.6600,0.5800,0.0900,0.5700,0.6300,0.3400,0.5100,0.4100,0.1000

In [8]:
elasticity_l.corr()

,탄력_왼쪽볼_R0,탄력_왼쪽볼_R1,탄력_왼쪽볼_R2,탄력_왼쪽볼_R3,탄력_왼쪽볼_R4,탄력_왼쪽볼_R5,탄력_왼쪽볼_R6,탄력_왼쪽볼_R7,탄력_왼쪽볼_R8,탄력_왼쪽볼_R9,탄력_왼쪽볼_Q0,탄력_왼쪽볼_Q1,탄력_왼쪽볼_Q2,탄력_왼쪽볼_Q3
탄력_왼쪽볼_R0,1.000000,0.439238,0.415010,0.990320,0.540022,-0.158100,-0.730418,0.240922,0.880060,0.242231,0.997904,0.415281,0.308044,0.578745
탄력_왼쪽볼_R1,0.439238,1.000000,-0.604993,0.469197,0.935787,-0.783988,-0.149024,-0.680002,-0.030044,0.355704,0.438920,-0.603878,-0.663679,-0.179358
탄력_왼쪽볼_R2,0.415010,-0.604993,1.000000,0.381571,-0.462282,0.676121,-0.493787,0.905490,0.781212,-0.143155,0.417520,0.991272,0.945620,0.736238
탄력_왼쪽볼_R3,0.990320,0.469197,0.381571,1.000000,0.577493,-0.161659,-0.689359,0.216048,0.858175,0.348653,0.991818,0.383928,0.280271,0.548567
탄력_왼쪽볼_R4,0.540022,0.935787,-0.462282,0.577493,1.000000,-0.716387,-0.224905,-0.575810,0.108699,0.454507,0.538713,-0.465411,-0.545595,-0.033502
탄력_왼쪽볼_R5,-0.158100,-0.783988,0.676121,-0.161659,-0.716387,1.000000,0.199104,0.859959,0.239225,-0.095933,-0.156415,0.707546,0.804826,0.129831
탄력_왼쪽볼_R6,-0.730418,-0.149024,-0.493787,-0.689359,-0.224905,0.199104,1.000000,-0.311844,-0.736720,0.088209,-0.731727,-0.483077,-0.381531,-0.600656
탄력_왼쪽볼_R7,0.240922,-0.680002,0.905490,0.216048,-0.575810,0.859959,-0.311844,1.000000,0.629528,-0.134143,0.243186,0.934001,0.980487,0.419923
탄력_왼쪽볼_R8,0.880060,-0.030044,0.781212,0.858175,0.108699,0.239225,-0.736720,0.629528,1.000000,0.083765,0.882508,0.781469,0.693351,0.739389
탄력_왼쪽볼_R9,0.242231,0.355704,-0.143155,0.348653,0.454507,-0.095933,0.088209,-0.134143,0.083765,1.000000,0.239128,-0.130046,-0.135722,-0.059174
탄력_왼쪽볼_Q0,0.997904,0.438920,0.417520,0.991818,0.538713,-0.156415,-0.731727,0.243186,0.882508,0.239128,1.000000,0.417882,0.310416,0.580429
탄력_왼쪽볼_Q1,0.415281,-0.603878,0.991272,0.383928,-0.465411,0.707546,-0.483077,0.934001,0.781469,-0.130046,0.417882,1.000000,0.971164,0.688720
탄력_왼쪽볼_Q2,0.308044,-0.663679,0.945620,0.280271,-0.545595,0.804826,-0.381531,0.980487,0.693351,-0.135722,0.310416,0.971164,1.000000,0.499781
탄력_왼쪽볼_Q3,0.578745,-0.179358,0.736238,0.548567,-0.033502,0.129831,-0.600656,0.419923,0.739389,-0.059174,0.580429,0.688720,0.499781,1.000000

In [9]:
elasticity_f.corr()

,탄력_이마_R0,탄력_이마_R1,탄력_이마_R2,탄력_이마_R3,탄력_이마_R4,탄력_이마_R5,탄력_이마_R6,탄력_이마_R7,탄력_이마_R8,탄력_이마_R9,탄력_이마_Q0,탄력_이마_Q1,탄력_이마_Q2,탄력_이마_Q3
탄력_이마_R0,1.000000,0.472648,0.258464,0.990419,0.513723,-0.428773,-0.746990,-0.063894,0.845156,-0.027373,0.999302,0.239426,0.047026,0.554296
탄력_이마_R1,0.472648,1.000000,-0.696960,0.485772,0.896279,-0.803325,-0.247105,-0.765548,-0.067007,0.117825,0.472812,-0.700719,-0.759326,-0.270250
탄력_이마_R2,0.258464,-0.696960,1.000000,0.238341,-0.570139,0.575472,-0.330271,0.815861,0.714650,-0.148524,0.258335,0.980982,0.890423,0.753452
탄력_이마_R3,0.990419,0.485772,0.238341,1.000000,0.520822,-0.419248,-0.707541,-0.074565,0.827848,0.095728,0.991106,0.218805,0.030214,0.534514
탄력_이마_R4,0.513723,0.896279,-0.570139,0.520822,1.000000,-0.746152,-0.255490,-0.698505,0.040242,0.082743,0.514073,-0.582735,-0.676903,-0.123401
탄력_이마_R5,-0.428773,-0.803325,0.575472,-0.419248,-0.746152,1.000000,0.434472,0.868559,-0.001627,0.050471,-0.429180,0.636119,0.796304,0.009013
탄력_이마_R6,-0.746990,-0.247105,-0.330271,-0.707541,-0.255490,0.434472,1.000000,-0.054643,-0.698561,0.275332,-0.747075,-0.311971,-0.154493,-0.520263
탄력_이마_R7,-0.063894,-0.765548,0.815861,-0.074565,-0.698505,0.868559,-0.054643,1.000000,0.389769,-0.092055,-0.064179,0.877238,0.974125,0.283389
탄력_이마_R8,0.845156,-0.067007,0.714650,0.827848,0.040242,-0.001627,-0.698561,0.389769,1.000000,-0.103057,0.845843,0.694661,0.511378,0.793012
탄력_이마_R9,-0.027373,0.117825,-0.148524,0.095728,0.082743,0.050471,0.275332,-0.092055,-0.103057,1.000000,-0.027180,-0.151641,-0.128517,-0.133512
탄력_이마_Q0,0.999302,0.472812,0.258335,0.991106,0.514073,-0.429180,-0.747075,-0.064179,0.845843,-0.027180,1.000000,0.239302,0.046875,0.554487
탄력_이마_Q1,0.239426,-0.700719,0.980982,0.218805,-0.582735,0.636119,-0.311971,0.877238,0.694661,-0.151641,0.239302,1.000000,0.943473,0.687863
탄력_이마_Q2,0.047026,-0.759326,0.890423,0.030214,-0.676903,0.796304,-0.154493,0.974125,0.511378,-0.128517,0.046875,0.943473,1.000000,0.411200
탄력_이마_Q3,0.554296,-0.270250,0.753452,0.534514,-0.123401,0.009013,-0.520263,0.283389,0.793012,-0.133512,0.554487,0.687863,0.411200,1.000000

In [10]:
elasticity_l.columns

Index(['탄력_왼쪽볼_R0', '탄력_왼쪽볼_R1', '탄력_왼쪽볼_R2', '탄력_왼쪽볼_R3', '탄력_왼쪽볼_R4',
       '탄력_왼쪽볼_R5', '탄력_왼쪽볼_R6', '탄력_왼쪽볼_R7', '탄력_왼쪽볼_R8', '탄력_왼쪽볼_R9',
       '탄력_왼쪽볼_Q0', '탄력_왼쪽볼_Q1', '탄력_왼쪽볼_Q2', '탄력_왼쪽볼_Q3'],
      dtype='object')

In [11]:
feature = ['탄력_왼쪽볼_R2', '탄력_왼쪽볼_R5', '탄력_왼쪽볼_R7',  '탄력_왼쪽볼_Q0', '탄력_왼쪽볼_Q1', '탄력_왼쪽볼_Q2', '탄력_왼쪽볼_Q3']
elasticity_l[feature].corr()

,탄력_왼쪽볼_R2,탄력_왼쪽볼_R5,탄력_왼쪽볼_R7,탄력_왼쪽볼_Q0,탄력_왼쪽볼_Q1,탄력_왼쪽볼_Q2,탄력_왼쪽볼_Q3
탄력_왼쪽볼_R2,1.000000,0.676121,0.905490,0.417520,0.991272,0.945620,0.736238
탄력_왼쪽볼_R5,0.676121,1.000000,0.859959,-0.156415,0.707546,0.804826,0.129831
탄력_왼쪽볼_R7,0.905490,0.859959,1.000000,0.243186,0.934001,0.980487,0.419923
탄력_왼쪽볼_Q0,0.417520,-0.156415,0.243186,1.000000,0.417882,0.310416,0.580429
탄력_왼쪽볼_Q1,0.991272,0.707546,0.934001,0.417882,1.000000,0.971164,0.688720
탄력_왼쪽볼_Q2,0.945620,0.804826,0.980487,0.310416,0.971164,1.000000,0.499781
탄력_왼쪽볼_Q3,0.736238,0.129831,0.419923,0.580429,0.688720,0.499781,1.000000

In [12]:
feature = ['탄력_왼쪽볼_R2', '탄력_왼쪽볼_R5', '탄력_왼쪽볼_R7', '탄력_왼쪽볼_Q1', '탄력_왼쪽볼_Q2', '탄력_왼쪽볼_Q3']
elasticity_l[feature].corr()

           탄력_왼쪽볼_R2  탄력_왼쪽볼_R5  탄력_왼쪽볼_R7  탄력_왼쪽볼_Q1  탄력_왼쪽볼_Q2  탄력_왼쪽볼_Q3
탄력_왼쪽볼_R2   1.000000   0.676121   0.905490   0.991272   0.945620   0.736238
탄력_왼쪽볼_R5   0.676121   1.000000   0.859959   0.707546   0.804826   0.129831
탄력_왼쪽볼_R7   0.905490   0.859959   1.000000   0.934001   0.980487   0.419923
탄력_왼쪽볼_Q1   0.991272   0.707546   0.934001   1.000000   0.971164   0.688720
탄력_왼쪽볼_Q2   0.945620   0.804826   0.980487   0.971164   1.000000   0.499781
탄력_왼쪽볼_Q3   0.736238   0.129831   0.419923   0.688720   0.499781   1.000000

In [13]:
# feature = ['탄력_왼쪽볼_R0', '탄력_왼쪽볼_R1', '탄력_왼쪽볼_R4', '탄력_왼쪽볼_R3','탄력_왼쪽볼_R8', '탄력_왼쪽볼_R9']
# # feature 리스트에 포함된 피쳐들의 값을 반대로 변환
# elasticity_l[feature] = 1 - elasticity_l[feature]
# elasticity_l

In [14]:
elasticity_l.columns

Index(['탄력_왼쪽볼_R0', '탄력_왼쪽볼_R1', '탄력_왼쪽볼_R2', '탄력_왼쪽볼_R3', '탄력_왼쪽볼_R4',
       '탄력_왼쪽볼_R5', '탄력_왼쪽볼_R6', '탄력_왼쪽볼_R7', '탄력_왼쪽볼_R8', '탄력_왼쪽볼_R9',
       '탄력_왼쪽볼_Q0', '탄력_왼쪽볼_Q1', '탄력_왼쪽볼_Q2', '탄력_왼쪽볼_Q3'],
      dtype='object')

# 탄력- 왼쪽볼

In [17]:
from sklearn.decomposition import PCA

features = ['탄력_왼쪽볼_R2', '탄력_왼쪽볼_R5', '탄력_왼쪽볼_R7', '탄력_왼쪽볼_Q1', '탄력_왼쪽볼_Q2', '탄력_왼쪽볼_Q3']
x = elasticity_l[features]


# PCA 적용
pca = PCA(n_components=1)  # 2개의 주성분으로 변환
principal_components = pca.fit_transform(x)

pca.explained_variance_ratio_

array([0.87202907])

In [18]:
# 결과
pca_components = pca.components_
print('printcipalComponents:\n', pca_components)

printcipalComponents:
 [[0.49400751 0.48669394 0.35349306 0.47488815 0.40447736 0.07076416]]

In [19]:
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
printcipalComponents = pca.fit_transform(x)
pca_l= pd.DataFrame(data=printcipalComponents, columns = ['elasticity_l'])
pd.concat([elasticity_l[features], pca_l], axis=1).corr()

,탄력_왼쪽볼_R2,탄력_왼쪽볼_R5,탄력_왼쪽볼_R7,탄력_왼쪽볼_Q1,탄력_왼쪽볼_Q2,탄력_왼쪽볼_Q3,elasticity_l
탄력_왼쪽볼_R2,1.000000,0.676121,0.905490,0.991272,0.945620,0.736238,0.952752
탄력_왼쪽볼_R5,0.676121,1.000000,0.859959,0.707546,0.804826,0.129831,0.858240
탄력_왼쪽볼_R7,0.905490,0.859959,1.000000,0.934001,0.980487,0.419923,0.980790
탄력_왼쪽볼_Q1,0.991272,0.707546,0.934001,1.000000,0.971164,0.688720,0.968644
탄력_왼쪽볼_Q2,0.945620,0.804826,0.980487,0.971164,1.000000,0.499781,0.986010
탄력_왼쪽볼_Q3,0.736238,0.129831,0.419923,0.688720,0.499781,1.000000,0.530627
elasticity_l,0.952752,0.858240,0.980790,0.968644,0.986010,0.530627,1.000000

# 탄력- 오른쪽볼

In [20]:
features = ['탄력_오른쪽볼_R2', '탄력_오른쪽볼_R5', '탄력_오른쪽볼_R7', '탄력_오른쪽볼_Q1', '탄력_오른쪽볼_Q2', '탄력_오른쪽볼_Q3']
x = elasticity_r[features]


# PCA 적용
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
principal_components = pca.fit_transform(x)

pca.explained_variance_ratio_

array([0.89118429])

In [21]:
# 결과
pca_components = pca.components_
print('printcipalComponents:\n', pca_components)

printcipalComponents:
 [[0.49218615 0.49767721 0.35299758 0.47070616 0.39831438 0.07241731]]

In [22]:
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
printcipalComponents = pca.fit_transform(x)
pca_r= pd.DataFrame(data=printcipalComponents, columns = ['elasticity_r'])
pd.concat([elasticity_r[features], pca_r], axis=1).corr()

,탄력_오른쪽볼_R2,탄력_오른쪽볼_R5,탄력_오른쪽볼_R7,탄력_오른쪽볼_Q1,탄력_오른쪽볼_Q2,탄력_오른쪽볼_Q3,elasticity_r
탄력_오른쪽볼_R2,1.000000,0.728258,0.907997,0.991000,0.949588,0.750017,0.957026
탄력_오른쪽볼_R5,0.728258,1.000000,0.889253,0.760310,0.841365,0.218692,0.886883
탄력_오른쪽볼_R7,0.907997,0.889253,1.000000,0.938461,0.983546,0.445443,0.981037
탄력_오른쪽볼_Q1,0.991000,0.760310,0.938461,1.000000,0.973864,0.704519,0.973093
탄력_오른쪽볼_Q2,0.949588,0.841365,0.983546,0.973864,1.000000,0.528900,0.987584
탄력_오른쪽볼_Q3,0.750017,0.218692,0.445443,0.704519,0.528900,1.000000,0.562209
elasticity_r,0.957026,0.886883,0.981037,0.973093,0.987584,0.562209,1.000000

# 탄력- 이마

In [23]:
features = ['탄력_이마_R2', '탄력_이마_R5', '탄력_이마_R7', '탄력_이마_Q1', '탄력_이마_Q2', '탄력_이마_Q3']
x = elasticity_f[features]


# PCA 적용
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
principal_components = pca.fit_transform(x)

pca.explained_variance_ratio_

array([0.82104588])

In [24]:
# 결과
pca_components = pca.components_
print('printcipalComponents:\n', pca_components)

printcipalComponents:
 [[0.50098068 0.50626333 0.32776388 0.47557721 0.38920697 0.08735498]]

In [25]:
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
printcipalComponents = pca.fit_transform(x)
pca_f= pd.DataFrame(data=printcipalComponents, columns = ['elasticity_f'])
pd.concat([elasticity_f[features], pca_f], axis=1).corr()

,탄력_이마_R2,탄력_이마_R5,탄력_이마_R7,탄력_이마_Q1,탄력_이마_Q2,탄력_이마_Q3,elasticity_f
탄력_이마_R2,1.000000,0.575472,0.815861,0.980982,0.890423,0.753452,0.922019
탄력_이마_R5,0.575472,1.000000,0.868559,0.636119,0.796304,0.009013,0.834611
탄력_이마_R7,0.815861,0.868559,1.000000,0.877238,0.974125,0.283389,0.963329
탄력_이마_Q1,0.980982,0.636119,0.877238,1.000000,0.943473,0.687863,0.953979
탄력_이마_Q2,0.890423,0.796304,0.974125,0.943473,1.000000,0.411200,0.980277
탄력_이마_Q3,0.753452,0.009013,0.283389,0.687863,0.411200,1.000000,0.481926
elasticity_f,0.922019,0.834611,0.963329,0.953979,0.980277,0.481926,1.000000

# 탄력- 턱

In [26]:
features = ['탄력_턱_R2', '탄력_턱_R5', '탄력_턱_R7', '탄력_턱_Q1', '탄력_턱_Q2', '탄력_턱_Q3']
elasticity_chin[features].corr()

          탄력_턱_R2   탄력_턱_R5   탄력_턱_R7   탄력_턱_Q1   탄력_턱_Q2   탄력_턱_Q3
탄력_턱_R2  1.000000  0.594833  0.883798  0.987883  0.924806  0.779643
탄력_턱_R5  0.594833  1.000000  0.803588  0.642707  0.758426  0.115840
탄력_턱_R7  0.883798  0.803588  1.000000  0.925631  0.984572  0.437254
탄력_턱_Q1  0.987883  0.642707  0.925631  1.000000  0.960694  0.726070
탄력_턱_Q2  0.924806  0.758426  0.984572  0.960694  1.000000  0.510412
탄력_턱_Q3  0.779643  0.115840  0.437254  0.726070  0.510412  1.000000

In [27]:
features = ['탄력_턱_R2', '탄력_턱_R5', '탄력_턱_R7', '탄력_턱_Q1', '탄력_턱_Q2', '탄력_턱_Q3']
x = elasticity_chin[features]


# PCA 적용
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
principal_components = pca.fit_transform(x)

pca.explained_variance_ratio_

array([0.84706645])

In [28]:
# 결과
pca_components = pca.components_
print('printcipalComponents:\n', pca_components)
['탄력_턱_R2', '탄력_턱_R5', '탄력_턱_R7', '탄력_턱_Q1', '탄력_턱_Q2', '탄력_턱_Q3']

printcipalComponents:
 [[-0.53129814 -0.43293852 -0.35049733 -0.49176077 -0.39555387 -0.09563803]]

['탄력_턱_R2', '탄력_턱_R5', '탄력_턱_R7', '탄력_턱_Q1', '탄력_턱_Q2', '탄력_턱_Q3']

In [29]:
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
printcipalComponents = pca.fit_transform(x)
pca_chin = pd.DataFrame(data=printcipalComponents, columns = ['elasticity_chin'])
pd.concat([elasticity_chin[features], pca_chin], axis=1).corr()

,탄력_턱_R2,탄력_턱_R5,탄력_턱_R7,탄력_턱_Q1,탄력_턱_Q2,탄력_턱_Q3,elasticity_chin
탄력_턱_R2,1.000000,0.594833,0.883798,0.987883,0.924806,0.779643,-0.952834
탄력_턱_R5,0.594833,1.000000,0.803588,0.642707,0.758426,0.115840,-0.795615
탄력_턱_R7,0.883798,0.803588,1.000000,0.925631,0.984572,0.437254,-0.971041
탄력_턱_Q1,0.987883,0.642707,0.925631,1.000000,0.960694,0.726070,-0.973708
탄력_턱_Q2,0.924806,0.758426,0.984572,0.960694,1.000000,0.510412,-0.982895
탄력_턱_Q3,0.779643,0.115840,0.437254,0.726070,0.510412,1.000000,-0.590640
elasticity_chin,-0.952834,-0.795615,-0.971041,-0.973708,-0.982895,-0.590640,1.000000

In [30]:
pd.concat([elasticity_chin[features].mean(axis = 1), pca_chin], axis=1)

             0  elasticity_chin
0     0.437600        -0.040565
1     0.469483        -0.118816
2     0.431550        -0.024970
3     0.462617        -0.105084
4     0.402350         0.050221
...        ...              ...
1067  0.475000        -0.137098
1068  0.498333        -0.197457
1069  0.446667        -0.061630
1070  0.498333        -0.198671
1071  0.538333        -0.308419

[1072 rows x 2 columns]

In [31]:
pca_chin['elasticity_chin'] = (-1) * pca_chin['elasticity_chin']
pca_chin[:5]

   elasticity_chin
0         0.040565
1         0.118816
2         0.024970
3         0.105084
4        -0.050221

In [32]:
pd.concat([elasticity_chin[features], pca_chin], axis=1).corr()

,탄력_턱_R2,탄력_턱_R5,탄력_턱_R7,탄력_턱_Q1,탄력_턱_Q2,탄력_턱_Q3,elasticity_chin
탄력_턱_R2,1.000000,0.594833,0.883798,0.987883,0.924806,0.779643,0.952834
탄력_턱_R5,0.594833,1.000000,0.803588,0.642707,0.758426,0.115840,0.795615
탄력_턱_R7,0.883798,0.803588,1.000000,0.925631,0.984572,0.437254,0.971041
탄력_턱_Q1,0.987883,0.642707,0.925631,1.000000,0.960694,0.726070,0.973708
탄력_턱_Q2,0.924806,0.758426,0.984572,0.960694,1.000000,0.510412,0.982895
탄력_턱_Q3,0.779643,0.115840,0.437254,0.726070,0.510412,1.000000,0.590640
elasticity_chin,0.952834,0.795615,0.971041,0.973708,0.982895,0.590640,1.000000

In [33]:
df_elasticity = pd.concat([pca_l, pca_r, pca_f, pca_chin], axis = 1)
df_elasticity

      elasticity_l  elasticity_r  elasticity_f  elasticity_chin
0         0.172421      0.167002      0.223858         0.040565
1         0.162408      0.148893      0.085328         0.118816
2         0.351000      0.327229      0.029464         0.024970
3        -0.024440     -0.101020      0.121606         0.105084
4         0.107418      0.196089      0.055014        -0.050221
...            ...           ...           ...              ...
1067      0.165861      0.118911      0.154654         0.137098
1068     -0.179578      0.068778      0.194772         0.197457
1069      0.037773      0.120812      0.160586         0.061630
1070      0.102503      0.134370      0.172271         0.198671
1071      0.025977      0.065273      0.024016         0.308419

[1072 rows x 4 columns]

주름 - 왼쪽 눈가

In [36]:
wrinkle_l = df.filter(regex='주름_왼쪽눈가')

In [37]:
wrinkle_l.columns

Index(['주름_왼쪽눈가_Ra', '주름_왼쪽눈가_Rq', '주름_왼쪽눈가_Rmax', '주름_왼쪽눈가_R3z', '주름_왼쪽눈가_Rt',
       '주름_왼쪽눈가_Rz=Rtm', '주름_왼쪽눈가_Rp', '주름_왼쪽눈가_Rv'],
      dtype='object')

In [38]:

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
features = wrinkle_l.columns
x = wrinkle_l[features]

# 데이터 정규화
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
# PCA 적용
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
principal_components = pca.fit_transform(x_scaled )

pca.explained_variance_ratio_

array([0.96161209])

In [39]:
# 결과
pca_components = pca.components_
print('printcipalComponents:\n', pca_components)

printcipalComponents:
 [[0.35713315 0.35825562 0.35736631 0.35375181 0.35784666 0.35818636
  0.33857742 0.34680172]]

In [40]:
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
printcipalComponents = pca.fit_transform(x)
pca_wrinkle_l= pd.DataFrame(data=printcipalComponents, columns = ['wrinkle_l'])

In [41]:
pca_wrinkle_l

       wrinkle_l
0     -84.890365
1     -81.805345
2    -107.443049
3     -64.082712
4     -60.511625
...          ...
1067  -56.723434
1068 -119.309776
1069 -101.877524
1070 -124.941809
1071  -28.349933

[1072 rows x 1 columns]

In [42]:
pd.concat([wrinkle_l[features], pca_wrinkle_l], axis=1).corr()

,주름_왼쪽눈가_Ra,주름_왼쪽눈가_Rq,주름_왼쪽눈가_Rmax,주름_왼쪽눈가_R3z,주름_왼쪽눈가_Rt,주름_왼쪽눈가_Rz=Rtm,주름_왼쪽눈가_Rp,주름_왼쪽눈가_Rv,wrinkle_l
주름_왼쪽눈가_Ra,1.000000,0.999277,0.968905,0.987207,0.968722,0.990622,0.910539,0.942929,0.978487
주름_왼쪽눈가_Rq,0.999277,1.000000,0.973947,0.986851,0.974615,0.993877,0.914304,0.949876,0.983430
주름_왼쪽눈가_Rmax,0.968905,0.973947,1.000000,0.953060,0.997558,0.973886,0.934748,0.972974,0.997783
주름_왼쪽눈가_R3z,0.987207,0.986851,0.953060,1.000000,0.954154,0.984504,0.907667,0.921366,0.965755
주름_왼쪽눈가_Rt,0.968722,0.974615,0.997558,0.954154,1.000000,0.977118,0.940711,0.972848,0.998661
주름_왼쪽눈가_Rz=Rtm,0.990622,0.993877,0.973886,0.984504,0.977118,1.000000,0.925226,0.946464,0.985054
주름_왼쪽눈가_Rp,0.910539,0.914304,0.934748,0.907667,0.940711,0.925226,1.000000,0.836661,0.936401
주름_왼쪽눈가_Rv,0.942929,0.949876,0.972974,0.921366,0.972848,0.946464,0.836661,1.000000,0.973626
wrinkle_l,0.978487,0.983430,0.997783,0.965755,0.998661,0.985054,0.936401,0.973626,1.000000

주름 오른쪽 눈가

In [43]:
wrinkle_r = df.filter(regex='주름_오른쪽눈가')

In [44]:
wrinkle_r.columns

Index(['주름_오른쪽눈가_Ra', '주름_오른쪽눈가_Rq', '주름_오른쪽눈가_Rmax', '주름_오른쪽눈가_R3z',
       '주름_오른쪽눈가_Rt', '주름_오른쪽눈가_Rz=Rtm', '주름_오른쪽눈가_Rp', '주름_오른쪽눈가_Rv'],
      dtype='object')

In [45]:

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
features = wrinkle_r.columns
x = wrinkle_r[features]

# 데이터 정규화
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
# PCA 적용
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
principal_components = pca.fit_transform(x_scaled )

pca.explained_variance_ratio_

array([0.95631975])

In [46]:
# 결과
pca_components = pca.components_
print('printcipalComponents:\n', pca_components)

printcipalComponents:
 [[0.35684582 0.35845907 0.3566627  0.351666   0.3575427  0.35864
  0.3417169  0.34649823]]

In [47]:
pca = PCA(n_components=1)  # 1개의 주성분으로 변환
printcipalComponents = pca.fit_transform(x)
pca_wrinkle_r= pd.DataFrame(data=printcipalComponents, columns = ['wrinkle_r'])

In [48]:
pca_wrinkle_r

       wrinkle_r
0    -124.644823
1     -84.683910
2     -92.011524
3     -77.381253
4     -82.519173
...          ...
1067  -85.340000
1068  -98.128895
1069  -87.273453
1070 -134.768013
1071  -18.541940

[1072 rows x 1 columns]

In [49]:
pd.concat([wrinkle_r[features], pca_wrinkle_r], axis=1).corr()

,주름_오른쪽눈가_Ra,주름_오른쪽눈가_Rq,주름_오른쪽눈가_Rmax,주름_오른쪽눈가_R3z,주름_오른쪽눈가_Rt,주름_오른쪽눈가_Rz=Rtm,주름_오른쪽눈가_Rp,주름_오른쪽눈가_Rv,wrinkle_r
주름_오른쪽눈가_Ra,1.000000,0.999042,0.952272,0.984522,0.955122,0.990767,0.910631,0.927110,0.967731
주름_오른쪽눈가_Rq,0.999042,1.000000,0.960768,0.983098,0.963759,0.993938,0.917634,0.936324,0.975117
주름_오른쪽눈가_Rmax,0.952272,0.960768,1.000000,0.928546,0.997486,0.962839,0.940239,0.975491,0.997332
주름_오른쪽눈가_R3z,0.984522,0.983098,0.928546,1.000000,0.932002,0.981966,0.901133,0.896221,0.947674
주름_오른쪽눈가_Rt,0.955122,0.963759,0.997486,0.932002,1.000000,0.966792,0.945799,0.975801,0.998456
주름_오른쪽눈가_Rz=Rtm,0.990767,0.993938,0.962839,0.981966,0.966792,1.000000,0.928861,0.933654,0.977709
주름_오른쪽눈가_Rp,0.910631,0.917634,0.940239,0.901133,0.945799,0.928861,1.000000,0.851902,0.943193
주름_오른쪽눈가_Rv,0.927110,0.936324,0.975491,0.896221,0.975801,0.933654,0.851902,1.000000,0.975067
wrinkle_r,0.967731,0.975117,0.997332,0.947674,0.998456,0.977709,0.943193,0.975067,1.000000

In [50]:
df_elasticity_wrinkle = pd.concat([df_elasticity, pca_wrinkle_r, pca_wrinkle_l], axis = 1)
df_elasticity_wrinkle

,elasticity_l,elasticity_r,elasticity_f,elasticity_chin,wrinkle_r,wrinkle_l
0,0.172421,0.167002,0.223858,0.040565,-124.644823,-84.890365
1,0.162408,0.148893,0.085328,0.118816,-84.683910,-81.805345
2,0.351000,0.327229,0.029464,0.024970,-92.011524,-107.443049
3,-0.024440,-0.101020,0.121606,0.105084,-77.381253,-64.082712
4,0.107418,0.196089,0.055014,-0.050221,-82.519173,-60.511625
...,...,...,...,...,...,...
1067,0.165861,0.118911,0.154654,0.137098,-85.340000,-56.723434
1068,-0.179578,0.068778,0.194772,0.197457,-98.128895,-119.309776
1069,0.037773,0.120812,0.160586,0.061630,-87.273453,-101.877524
1070,0.102503,0.134370,0.172271,0.198671,-134.768013,-124.941809
1071,0.025977,0.065273,0.024016,0.308419,-18.541940,-28.349933

In [51]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# 기존 데이터프레임과 칼럼 선택
extra = df[['수분_이마', '수분_오른쪽볼', '수분_왼쪽볼', '수분_턱', '스팟개수_정면', '모공개수_오른쪽볼', '모공개수_왼쪽볼']]
features = extra.columns
x = extra[features]

# 데이터 정규화
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# 데이터 프레임으로 변환
x_scaled_df = pd.DataFrame(x_scaled, columns=features)

# 결과 출력 (선택사항)
x_scaled_df.head()

      수분_이마   수분_오른쪽볼    수분_왼쪽볼      수분_턱   스팟개수_정면  모공개수_오른쪽볼  모공개수_왼쪽볼
0 -0.756963  1.346216  0.865548  1.605766 -0.191426  -0.699112 -0.571023
1  1.497360  0.163617  0.026358  0.435659 -0.019258  -0.520156 -0.566496
2 -0.483370 -0.315944 -0.457604 -0.333638 -1.991366  -1.110925 -1.288556
3 -0.244617 -0.859767 -0.876715  0.189077  2.062411  -0.017788  0.035598
4  0.336384  0.163617 -0.199168  0.835546 -1.083570  -1.361031 -1.130111

In [52]:
df_total = pd.concat([df_elasticity_wrinkle, x_scaled_df], axis = 1)

In [54]:
df_total

,elasticity_l,elasticity_r,elasticity_f,elasticity_chin,wrinkle_r,wrinkle_l,수분_이마,수분_오른쪽볼,수분_왼쪽볼,수분_턱,스팟개수_정면,모공개수_오른쪽볼,모공개수_왼쪽볼
0,0.172421,0.167002,0.223858,0.040565,-124.644823,-84.890365,-0.756963,1.346216,0.865548,1.605766,-0.191426,-0.699112,-0.571023
1,0.162408,0.148893,0.085328,0.118816,-84.683910,-81.805345,1.497360,0.163617,0.026358,0.435659,-0.019258,-0.520156,-0.566496
2,0.351000,0.327229,0.029464,0.024970,-92.011524,-107.443049,-0.483370,-0.315944,-0.457604,-0.333638,-1.991366,-1.110925,-1.288556
3,-0.024440,-0.101020,0.121606,0.105084,-77.381253,-64.082712,-0.244617,-0.859767,-0.876715,0.189077,2.062411,-0.017788,0.035598
4,0.107418,0.196089,0.055014,-0.050221,-82.519173,-60.511625,0.336384,0.163617,-0.199168,0.835546,-1.083570,-1.361031,-1.130111
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,0.165861,0.118911,0.154654,0.137098,-85.340000,-56.723434,0.677606,2.401252,2.607812,2.036130,-1.193132,-1.085052,-1.243286
1068,-0.179578,0.068778,0.194772,0.197457,-98.128895,-119.309776,-1.133025,0.036054,-0.716040,0.712717,-1.756591,-1.535674,-1.571495
1069,0.037773,0.120812,0.160586,0.061630,-87.273453,-101.877524,2.317114,2.337950,2.414227,2.067530,-1.459210,-0.548186,-0.600449
1070,0.102503,0.134370,0.172271,0.198671,-134.768013,-124.941809,1.599829,1.825778,1.510186,1.636243,-1.803546,-1.223041,-1.381360
1071,0.025977,0.065273,0.024016,0.308419,-18.541940,-28.349933,1.326237,1.538041,1.510186,0.004372,-0.332291,0.790746,0.126138

In [55]:
df_total.columns

Index(['elasticity_l', 'elasticity_r', 'elasticity_f', 'elasticity_chin',
       'wrinkle_r', 'wrinkle_l', '수분_이마', '수분_오른쪽볼', '수분_왼쪽볼', '수분_턱',
       '스팟개수_정면', '모공개수_오른쪽볼', '모공개수_왼쪽볼'],
      dtype='object')

In [56]:
df_total.rename(columns = {'수분_이마': 'moisture_f',
                           '수분_오른쪽볼':'moisture_r',
                           '수분_왼쪽볼':'moisture_l',
                           '수분_턱':'moisture_chin',
                           '스팟개수_정면':'spot_front',
                           '모공개수_오른쪽볼':'pore_r',
                           '모공개수_왼쪽볼':'pore_l'}, inplace=True)

In [57]:
df_total

,elasticity_l,elasticity_r,elasticity_f,elasticity_chin,wrinkle_r,wrinkle_l,moisture_f,moisture_r,moisture_l,moisture_chin,spot_front,pore_r,pore_l
0,0.172421,0.167002,0.223858,0.040565,-124.644823,-84.890365,-0.756963,1.346216,0.865548,1.605766,-0.191426,-0.699112,-0.571023
1,0.162408,0.148893,0.085328,0.118816,-84.683910,-81.805345,1.497360,0.163617,0.026358,0.435659,-0.019258,-0.520156,-0.566496
2,0.351000,0.327229,0.029464,0.024970,-92.011524,-107.443049,-0.483370,-0.315944,-0.457604,-0.333638,-1.991366,-1.110925,-1.288556
3,-0.024440,-0.101020,0.121606,0.105084,-77.381253,-64.082712,-0.244617,-0.859767,-0.876715,0.189077,2.062411,-0.017788,0.035598
4,0.107418,0.196089,0.055014,-0.050221,-82.519173,-60.511625,0.336384,0.163617,-0.199168,0.835546,-1.083570,-1.361031,-1.130111
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,0.165861,0.118911,0.154654,0.137098,-85.340000,-56.723434,0.677606,2.401252,2.607812,2.036130,-1.193132,-1.085052,-1.243286
1068,-0.179578,0.068778,0.194772,0.197457,-98.128895,-119.309776,-1.133025,0.036054,-0.716040,0.712717,-1.756591,-1.535674,-1.571495
1069,0.037773,0.120812,0.160586,0.061630,-87.273453,-101.877524,2.317114,2.337950,2.414227,2.067530,-1.459210,-0.548186,-0.600449
1070,0.102503,0.134370,0.172271,0.198671,-134.768013,-124.941809,1.599829,1.825778,1.510186,1.636243,-1.803546,-1.223041,-1.381360
1071,0.025977,0.065273,0.024016,0.308419,-18.541940,-28.349933,1.326237,1.538041,1.510186,0.004372,-0.332291,0.790746,0.126138

In [58]:
df = pd.concat([df[['ID']],df_total], axis = 1)

In [60]:
df.describe()

,ID,elasticity_l,elasticity_r,elasticity_f,elasticity_chin,wrinkle_r,wrinkle_l,moisture_f,moisture_r,moisture_l,moisture_chin,spot_front,pore_r,pore_l
count,1072.000000,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1.072000e+03,1072.000000,1.072000e+03
mean,548.371269,1.988459e-17,3.314099e-18,9.942296e-17,-3.314099e-17,-1.951341e-14,5.938865e-15,1.000858e-15,-3.645508e-16,1.988459e-16,-7.324158e-16,9.279476e-17,0.000000,3.976918e-17
std,316.529379,1.850055e-01,1.922370e-01,1.971835e-01,1.915332e-01,7.434506e+01,7.737955e+01,1.000467e+00,1.000467e+00,1.000467e+00,1.000467e+00,1.000467e+00,1.000467,1.000467e+00
min,1.000000,-5.096976e-01,-5.672632e-01,-5.563268e-01,-6.593682e-01,-1.558599e+02,-1.568120e+02,-3.659916e+00,-3.353488e+00,-3.910190e+00,-3.782085e+00,-2.241792e+00,-1.977672,-1.972137e+00
25%,272.750000,-1.360342e-01,-1.344460e-01,-1.364740e-01,-1.239016e-01,-5.109430e+01,-5.424532e+01,-6.291323e-01,-6.353324e-01,-6.192476e-01,-6.420962e-01,-7.431468e-01,-0.787511,-7.956769e-01
50%,552.500000,5.582388e-03,7.471781e-03,1.516065e-02,-1.076621e-03,-6.470850e+00,-1.021427e+01,2.897623e-02,3.605391e-02,-5.583623e-03,9.672472e-02,-3.490960e-02,-0.065222,-8.550033e-02
75%,820.250000,1.264521e-01,1.274431e-01,1.368900e-01,1.285764e-01,4.110287e+01,4.073326e+01,6.522453e-01,6.829826e-01,7.039049e-01,6.822403e-01,7.476729e-01,0.674856,6.427844e-01
max,1100.000000,5.710815e-01,6.789607e-01,5.630734e-01,5.571409e-01,4.824707e+02,4.579296e+02,3.478090e+00,3.201161e+00,3.478944e+00,3.083408e+00,2.844994e+00,3.242219,3.523668e+00

In [61]:
path = '/content/drive/MyDrive/Final_project_2조/02_2. 전처리 및 EDA_이미지/data/train_val_dataset_v2.csv'
df.to_csv(path)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# 사용할 feature 목록
features = df_total.columns

# 데이터프레임에서 해당 feature 선택
x = df_total[features]

# Min-Max 정규화
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

# 정규화된 데이터를 데이터프레임으로 변환
columns  = df_total.columns
df_total= pd.DataFrame(x_scaled, columns=columns)
df_total

,elasticity_l,elasticity_r,elasticity_f,elasticity_chin,wrinkle_r,wrinkle_l,moisture_f,moisture_r,moisture_l,moisture_chin,spot_front,pore_r,pore_l
0,0.631136,0.589192,0.696966,0.575362,0.048901,0.116995,0.406690,0.717003,0.646319,0.784773,0.403077,0.244940,0.254942
1,0.621871,0.574661,0.573213,0.639686,0.111503,0.122013,0.722509,0.536582,0.532748,0.614340,0.436923,0.279223,0.255766
2,0.796368,0.717762,0.523307,0.562542,0.100024,0.080309,0.445019,0.463418,0.467252,0.502287,0.049231,0.166047,0.124382
3,0.448989,0.374125,0.605622,0.628399,0.122944,0.150843,0.478467,0.380451,0.410532,0.578423,0.846154,0.375465,0.365321
4,0.570992,0.612532,0.546132,0.500734,0.114895,0.156652,0.559862,0.536582,0.502227,0.672585,0.227692,0.118133,0.153213
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,0.625066,0.550603,0.635144,0.654714,0.110476,0.162814,0.607666,0.877963,0.882106,0.847458,0.206154,0.171004,0.132619
1068,0.305446,0.510375,0.670983,0.704331,0.090441,0.061005,0.354005,0.517120,0.432277,0.654695,0.095385,0.084676,0.072900
1069,0.506551,0.552128,0.640444,0.592678,0.107447,0.089362,0.837353,0.868306,0.855908,0.852031,0.153846,0.273854,0.249588
1070,0.566444,0.563007,0.650883,0.705329,0.033042,0.051843,0.736865,0.790167,0.733560,0.789212,0.086154,0.144568,0.107496
1071,0.495638,0.507562,0.518440,0.795545,0.215120,0.208969,0.698536,0.746269,0.733560,0.551520,0.375385,0.530359,0.381796

In [ ]:
df = pd.concat([df[['ID']],df_total], axis = 1)

In [ ]:
df

,ID,elasticity_l,elasticity_r,elasticity_f,elasticity_chin,wrinkle_r,wrinkle_l,moisture_f,moisture_r,moisture_l,moisture_chin,spot_front,pore_r,pore_l
0,1,0.631136,0.589192,0.696966,0.575362,0.048901,0.116995,0.406690,0.717003,0.646319,0.784773,0.403077,0.244940,0.254942
1,2,0.621871,0.574661,0.573213,0.639686,0.111503,0.122013,0.722509,0.536582,0.532748,0.614340,0.436923,0.279223,0.255766
2,3,0.796368,0.717762,0.523307,0.562542,0.100024,0.080309,0.445019,0.463418,0.467252,0.502287,0.049231,0.166047,0.124382
3,4,0.448989,0.374125,0.605622,0.628399,0.122944,0.150843,0.478467,0.380451,0.410532,0.578423,0.846154,0.375465,0.365321
4,6,0.570992,0.612532,0.546132,0.500734,0.114895,0.156652,0.559862,0.536582,0.502227,0.672585,0.227692,0.118133,0.153213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,1096,0.625066,0.550603,0.635144,0.654714,0.110476,0.162814,0.607666,0.877963,0.882106,0.847458,0.206154,0.171004,0.132619
1068,1097,0.305446,0.510375,0.670983,0.704331,0.090441,0.061005,0.354005,0.517120,0.432277,0.654695,0.095385,0.084676,0.072900
1069,1098,0.506551,0.552128,0.640444,0.592678,0.107447,0.089362,0.837353,0.868306,0.855908,0.852031,0.153846,0.273854,0.249588
1070,1099,0.566444,0.563007,0.650883,0.705329,0.033042,0.051843,0.736865,0.790167,0.733560,0.789212,0.086154,0.144568,0.107496
1071,1100,0.495638,0.507562,0.518440,0.795545,0.215120,0.208969,0.698536,0.746269,0.733560,0.551520,0.375385,0.530359,0.381796

In [ ]:
df.describe()

,ID,elasticity_l,elasticity_r,elasticity_f,elasticity_chin,wrinkle_r,wrinkle_l,moisture_f,moisture_r,moisture_l,moisture_chin,spot_front,pore_r,pore_l
count,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000
mean,548.371269,0.471602,0.455186,0.496987,0.542017,0.244168,0.255086,0.512736,0.511620,0.529181,0.550883,0.440709,0.378872,0.358844
std,316.529379,0.171178,0.154256,0.176151,0.157445,0.116468,0.125873,0.140161,0.152635,0.135397,0.145724,0.196680,0.191664,0.182042
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,272.750000,0.345735,0.347303,0.375069,0.440167,0.164124,0.166845,0.424598,0.414691,0.445376,0.457358,0.294615,0.228005,0.214065
50%,552.500000,0.476767,0.461181,0.510530,0.541132,0.234031,0.238471,0.516796,0.517120,0.528425,0.564972,0.433846,0.366378,0.343287
75%,820.250000,0.588603,0.557449,0.619275,0.647710,0.308559,0.321347,0.604113,0.615818,0.624443,0.650256,0.587692,0.508158,0.475803
max,1100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
path = '/content/drive/MyDrive/Final_project_2조/02_2. 전처리 및 EDA_이미지/data/train_val_dataset.csv'
df.to_csv(path)